# どのイメージを基にするか
FROM centos:latest

# RUN: docker buildするときに実行される
RUN echo "now building..."

# ホストのindex.htmlをImage内にコピー
#ADD ../index.php

# CMD: docker runするときに実行される
CMD echo "now running..."

#ポート80を開ける
#EXPOSE 80